var R=require("../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/auth/route.js")
R.c("server/chunks/node_modules_next_95ba55b9._.js")
R.c("server/chunks/node_modules_next-auth_804ae15a._.js")
R.c("server/chunks/node_modules_openid-client_d15f72b3._.js")
R.c("server/chunks/node_modules_jose_dist_node_cjs_bd88468e._.js")
R.c("server/chunks/node_modules_f49efdd4._.js")
R.c("server/chunks/[root-of-the-server]__1ff43cfb._.js")
R.c("server/chunks/_next-internal_server_app_api_admin_auth_route_actions_a3e5244b.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/auth/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/auth/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
