var R=require("../../../../../chunks/[turbopack]_runtime.js")("server/app/api/admin/service-categories/[id]/route.js")
R.c("server/chunks/node_modules_next_44c8f39a._.js")
R.c("server/chunks/node_modules_next-auth_b9efd365._.js")
R.c("server/chunks/node_modules_openid-client_d15f72b3._.js")
R.c("server/chunks/node_modules_jose_dist_node_cjs_bd88468e._.js")
R.c("server/chunks/node_modules_f49efdd4._.js")
R.c("server/chunks/[root-of-the-server]__7d366442._.js")
R.c("server/chunks/ce889_server_app_api_admin_service-categories_[id]_route_actions_8e54dc1f.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/service-categories/[id]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/admin/service-categories/[id]/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
