var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/clinic/questions/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__f403f205._.js")
R.c("server/chunks/ssr/_a3b9117b._.js")
R.c("server/chunks/ssr/_1d37e3ea._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3d372004._.js")
R.c("server/chunks/ssr/node_modules_27c026a2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_982e7503._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/src_942f9040._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_0f6131ce._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_clinic_layout_tsx_f91c2001._.js")
R.c("server/chunks/ssr/src_app_clinic_questions_layout_tsx_95674a34._.js")
R.c("server/chunks/ssr/_next-internal_server_app_clinic_questions_page_actions_cd920684.js")
R.m(9119)
module.exports=R.m(9119).exports
